# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c21db656a12898637eefb5b661f505fafddda731d933db397a9ffea500b5bff3fc6a1260ab8cc5b27c5e5fb45ab5953bdf856af5b3ad06215fde4ac49992ac

test:
  secret_key_base: 9764048b2ec75a2fa52bd4efdcda275bb0e36dc5b54bfa4336a0136a77f8648310681f7f4bc8c245d647d93a21875fbee1ea2c499dd2b04e81dacffdd3e3705c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
